### ISSUE TITLE
추가 입력폼 필수 여부 체크 부분과 상품판매옵션 관련 문의드립니다. 

### ISSUE THREAD

**Issue by jun7051** [Waterticket/rx-module-hotopay#36]
라이믹스, hotopay 최신 버젼입니다.

hotopay > 추가입력폼 설정에서
1.  확장변수 생성 > 필수여부에 체크를 한 다음 저장 후 다시 체크 해제를 하고 저장을 하면 체크해제가 되어 있지 않고 체크 표시가 되어 있습니다.
2.  확장변수 생성 > 필수 여부 체크를 하지 않고 저장을 하고 다시 열어 보면 필수 여부에 체크가 표시되어 있는데 버그 인것 같아서 제보드립니다.

*상품판매옵션은 필수로 입력하게끔 되어 있는데요. 혹시 이부분을 선택입력사항으로 변경 할 수 없을까요?
( 옵션이 없는 상품은 구매페이지에서 옵션이 노출되지 않으면 좋을 것 같습니다. )
![2023-10-13 15;19;19](https://github.com/Waterticket/rx-module-hotopay/assets/19809054/4eb36c47-00ca-435b-a723-e38d71478e81)

자료 감사합니다. ^^

**Comment by Waterticket** [comment]
버그 제보 감사드립니다.

위 이슈는 1.4.6 버전에서 해결되었습니다.
https://github.com/Waterticket/rx-module-hotopay/releases/tag/1.4.6
