### ISSUE TITLE
카드 결제 완료 후 발생하는 에러 메시지 문의드립니다.

### ISSUE THREAD

**Issue by jun7051** [Waterticket/rx-module-hotopay#38]
1. rhymix_version : 2.1.9  / php : 7.2.33-1+ubuntu18.04.1 
2. Hoto Pay 1.4.6 / Toss Payments PG사 설정 및 결제완료 알림설정 : 쪽지, 메일 설정 / 우리메일(woorimail )
3.  카드 결제 완료 된 바로 다음 홈페이지 페이지에서 아래 메시지가 발생합니다.

![th0001_b002](https://github.com/Waterticket/rx-module-hotopay/assets/19809054/9e2c1942-c129-4dd6-8f03-ea8eed9f6e2a)

토스페이먼츠에서 확인 해보면 페이지 에러와 상관없이 결제가 정상 접수되었는데 고객 입장에서는 결제완료 후 바로 보이는 페이지 에러메시지로 인해 자신의 카드 결제가 제대로 처리가 안된걸로 인지해서 문의를 해 온 경우인데 혹시 증상 재현이 되시나요?

4. 위와 관계없이 고객 결제 시 관리자( 운영자 )에게 별도 알림 쪽지나 이메일 또는 다른 방법으로의 결제 알림은 현재 기능에서는 없는거죠?

**Comment by Waterticket** [comment]
### 고객 결제 시 관리자( 운영자 )에게 별도 알림 쪽지나 이메일 또는 다른 방법으로의 결제 알림

알림설정 > 최하단 `관리자 알림 설정` 항목을 참고해주세요

**Comment by Waterticket** [comment]
혹시 결제실패 메세지가 뜨는 유저의 이메일 혹은 닉네임이 설정되어있지 않거나, 비회원으로 구매를 진행하셨을까요?

**Comment by jun7051** [comment]
1. 회원에게만 상품 결제 url 버튼이 노출되구요. 에러를 발견한 실 결제 회원과 테스트 아이디 역시 닉네임과 실제 사용중인 이메일 주소가 모두 설정된 상태입니다.
( 혹시 필요하시면 xetown 쪽지를 통해 테스트를 해 보실 수 있는 정보을 보내드리겠습니다. )



2.  시스템 설정 > 알림설정 > 이메일 > 기본 발신자 주소 ( 사용중인 이메일 주소 입력 )
hotopay > 알림 설정 > 관리자 알림 설정 < 관리자 알림 활성화  체크
![2023-11-26 19;18;14](https://github.com/Waterticket/rx-module-hotopay/assets/19809054/a87eecd1-6c96-4708-98a4-a6290abafc6a)

위 시스템 설정에서 입력한 이메일로  테스트 회원 로그인 > 결제 완료 후 결제가 완료되었는데 알림 메일이 오질 않는데요. 

메일 ,SMS 및 푸시 알림 관리 모듈 > 메일 테스트 발송을 해보면 관리자 멩일로 알림을 정상 발송되고 있습니다.

**Comment by Waterticket** [comment]
테스트 계정 아래 페이지에 글로 남겨주시면 확인해드리겠습니다.

https://potatosoft.kr/membership

관리자 계정, 결제해볼 테스트 상품 전달 부탁드립니다

**Comment by jun7051** [comment]
> 테스트 계정 아래 페이지에 글로 남겨주시면 확인해드리겠습니다.
> 
> https://potatosoft.kr/membership
> 
> 관리자 계정, 결제해볼 테스트 상품 전달 부탁드립니다

네 방금 해당 내용을 기재 했습니다. 감사합니다.
