### ISSUE TITLE
관리자설정>상품목록>수정을 누르면 첫번째 위와 같은 오류가 발생함.(새로고침시 정상)

### ISSUE THREAD

**Issue by eondcom** [Waterticket/rx-module-hotopay#42]
Error #0 "Attempt to assign property "product_option" on null" in modules/hotopay/hotopay.admin.view.php on line 274
객체를 먼저 선언하지 않고 속성을 추가하려 하고 있습니다. 오래된 자료에서 종종 사용하던 코딩 방식이나 최근 PHP에서는 허용되지 않으니, 에러 메시지에 포함된 파일명과 줄 번호를 참고하여 수정하세요.
modules/hotopay/hotopay.admin.view.php:274

관리자설정>상품목록>수정을 누르면 첫번째 위와 같은 오류가 발생함.
두번째 클릭시는 정상 이동됨.

**Comment by Waterticket** [comment]
1.4.9 패치로 해결되었습니다.
