### ISSUE TITLE
상품정보가 없습니다.

### ISSUE THREAD

**Issue by eondcom** [Waterticket/rx-module-hotopay#44]
게시물 보기 > 상품 카트에 담기 > 상품정보가 없습니다. 
다시 상품카트에 담기 > 정상적으로 동작.

항상 2번 동작해야 동작되는 버그가 있는데 원인을 모르겠습니다;

**Comment by Waterticket** [comment]
1.4.9 패치에서 해결되었습니다.
업그레이드 후 확인 부탁드립니다.
