### ISSUE TITLE
레이아웃 설정 기능 추가

### ISSUE THREAD

**Issue by eondcom** [Waterticket/rx-module-hotopay#46]
레이아웃을 2개 사용 중입니다.
기본 사이트가 있고 결제용으로 별개의 레이아웃을 사용하는데요
호토페이 자체에서 레이아웃 설정 기능이 없어서 기본 사이트로 결제 기능이 동작합니다.
호토페이 자체에서 레이아웃을 추가로 설정할 수 있으면 좋겠습니다.

**Comment by Waterticket** [comment]
[사이트 메뉴 편집] > [unlinked] > [Hoto Pay] 항목의 디자인에서 레이아웃을 변경해보세요.
라이믹스 기본 기능에서 수정이 가능하여, Hotopay에 해당 기능을 넣을 계획은 없습니다.
